"""empty message

Revision ID: 3077b58b0e22
Revises: 
Create Date: 2020-03-09 09:25:55.627016

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3077b58b0e22'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'login', ['username'])
    op.add_column('registration', sa.Column('fullname', sa.String(length=64), nullable=True))
    op.drop_column('registration', '_fullname')
    op.create_unique_constraint(None, 'role', ['role_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role', type_='unique')
    op.add_column('registration', sa.Column('_fullname', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('registration', 'fullname')
    op.drop_constraint(None, 'login', type_='unique')
    # ### end Alembic commands ###
